[package]
name = "hello_world"
version = "0.1.0"
authors = ["Jane Doe <nobody@email.com>"]
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
